development:
  dialect: "sqlite3"
  database: /Users/joshuagrafton/go/src/github.com/GraftonJ/blog_app_blog_app_development.sqlite

test:
  dialect: "sqlite3"
  database: /Users/joshuagrafton/go/src/github.com/GraftonJ/blog_app_blog_app_test.sqlite

production:
  dialect: "sqlite3"
  database: /Users/joshuagrafton/go/src/github.com/GraftonJ/blog_app_blog_app_production.sqlite
